### ISSUE TITLE
Fail on identification of TIRs (EDTA v 1.8) with the step-by-step installation

### ISSUE THREAD

**Issue by Tkastylevsky** [oushujun/EDTA#56] opened 2020-02-11 10:21 UTC
Hello,
I'm currently trying to run EDTA on the cluster of my laboratory, and I encounter an issue that looks similar to the one listed below in the EDTA issues, except I'm running on the 1.8 version. i installed it through the step by step conda installation (for some reason, the one line conda installation doesn't want to work on my devices). 
I encounter this error : 

```
Mon Feb 10 17:57:54 CET 2020	EDTA_raw: Check dependencies, prepare working directories.

Mon Feb 10 17:58:14 CET 2020	Start to find LTR candidates.

Mon Feb 10 17:58:14 CET 2020	Identify LTR retrotransposon candidates from scratch.

Mon Feb 10 18:39:20 CET 2020	Finish finding LTR candidates.

Mon Feb 10 18:39:20 CET 2020	Start to find TIR candidates.

Mon Feb 10 18:39:20 CET 2020	Identify TIR candidates from scratch.

Species: others
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/beegfs/data/tkastylevsky/programs/EDTA/bin/TIR-Learner2.4/Module3_New/getDataset.py", line 11, in <module>
    from sklearn.preprocessing import LabelEncoder, OneHotEncoder
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/sklearn/preprocessing/__init__.py", line 8, in <module>
    from .data import Binarizer
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 18, in <module>
    from scipy import stats
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/scipy/stats/__init__.py", line 348, in <module>
    from .stats import *
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/scipy/stats/stats.py", line 177, in <module>
    from . import distributions
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/scipy/stats/_continuous_distns.py", line 15, in <module>
    from scipy._lib._numpy_compat import broadcast_to
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/scipy/_lib/_numpy_compat.py", line 10, in <module>
    from numpy.testing.nosetester import import_nose
ModuleNotFoundError: No module named 'numpy.testing.nosetester'
cat: '*-+-DTA.fa': No such file or directory
cat: '*-+-DTC.fa': No such file or directory
cat: '*-+-DTH.fa': No such file or directory
cat: '*-+-DTM.fa': No such file or directory
cat: '*-+-DTT.fa': No such file or directory
cat: '*-+-NonTIR.fa': No such file or directory
cat: '*-+-*-+-*.gff3': No such file or directory
rm: cannot remove '*-+-*-+-*.gff3': No such file or directory
Traceback (most recent call last):
  File "/beegfs/data/tkastylevsky/programs/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/beegfs/data/tkastylevsky/programs/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/beegfs/data/tkastylevsky/programs/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/beegfs/data/tkastylevsky/programs/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
mv: cannot stat 'TIR-Learner/*FinalAnn*.gff3': No such file or directory
mv: cannot stat 'TIR-Learner/*FinalAnn*.fa': No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /beegfs/data/tkastylevsky/programs/EDTA/util/rename_tirlearner.pl line 18.
Warning: LOC list galgal6_chr1.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!

Mon Feb 10 21:29:38 CET 2020	Start to find Helitron candidates.

Mon Feb 10 21:29:38 CET 2020	Identify Helitron candidates from scratch.

Tue Feb 11 01:27:12 CET 2020	Finish finding Helitron candidates.

Tue Feb 11 01:27:12 CET 2020	Execution of EDTA_raw.pl is finished!

ERROR: Raw TIR results not found in galgal6_chr1.fa.mod.EDTA.raw/galgal6_chr1.fa.mod.TIR.raw.fa at /beegfs/data/tkastylevsky/programs/EDTA/EDTA.pl line 368.
```

thanks in advance,

**Comment by oushujun** [comment] 2020-02-13 00:26
Seems like python packages were not correctly installed. You may want to
remove versions in the step by step and see if it works. You may also
create a new conda env for less conflicts for the quick installation.

Shujun

**Comment by Tkastylevsky** [comment] 2020-02-13 16:38
Hello, 
I did as you suggested, I completely removed my EDTA conda env, and reinstalled it. I then ran EDTA_raw.pl script separately for each kind of TE, and got the same result...

```
Thu Feb 13 15:27:09 CET 2020	EDTA_raw: Check dependencies, prepare working directories.

Thu Feb 13 15:27:14 CET 2020	Start to find TIR candidates.

Thu Feb 13 15:27:14 CET 2020	Identify TIR candidates from scratch.

Species: others
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/beegfs/data/tkastylevsky/programs/EDTA/bin/TIR-Learner2.4/Module3_New/getDataset.py", line 11, in <module>
    from sklearn.preprocessing import LabelEncoder, OneHotEncoder
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/sklearn/preprocessing/__init__.py", line 8, in <module>
    from .data import Binarizer
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 18, in <module>
    from scipy import stats
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/scipy/stats/__init__.py", line 348, in <module>
    from .stats import *
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/scipy/stats/stats.py", line 177, in <module>
    from . import distributions
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/scipy/stats/_continuous_distns.py", line 15, in <module>
    from scipy._lib._numpy_compat import broadcast_to
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/scipy/_lib/_numpy_compat.py", line 10, in <module>
    from numpy.testing.nosetester import import_nose
ModuleNotFoundError: No module named 'numpy.testing.nosetester'
cat: '*-+-DTA.fa': No such file or directory
cat: '*-+-DTC.fa': No such file or directory
cat: '*-+-DTH.fa': No such file or directory
cat: '*-+-DTM.fa': No such file or directory
cat: '*-+-DTT.fa': No such file or directory
cat: '*-+-NonTIR.fa': No such file or directory
cat: '*-+-*-+-*.gff3': No such file or directory
rm: cannot remove '*-+-*-+-*.gff3': No such file or directory
Traceback (most recent call last):
  File "/beegfs/data/tkastylevsky/programs/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/beegfs/data/tkastylevsky/programs/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/beegfs/data/tkastylevsky/programs/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/beegfs/data/tkastylevsky/programs/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/beegfs/home/tkastylevsky/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
mv: cannot stat 'TIR-Learner/*FinalAnn*.gff3': No such file or directory
mv: cannot stat 'TIR-Learner/*FinalAnn*.fa': No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /beegfs/data/tkastylevsky/programs/EDTA/util/rename_tirlearner.pl line 18.
Warning: LOC list galgal6_chr1.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!

Thu Feb 13 17:10:36 CET 2020	Execution of EDTA_raw.pl is finished!


```

In case it can help, here is the code I use to launch EDTA on my cluster : 

```
#!/bin/bash 
#SBATCH --job-name=EDTA_galgal6_chr1.fatir
#SBATCH --partition=normal
#SBATCH --output=/beegfs/data/tkastylevsky/scripts/subscripts/std_out_EDTA_galgal6_chr1.fatir
#SBATCH --error=/beegfs/data/tkastylevsky/scripts/subscripts/std_err_EDTA_galgal6_chr1.fatir
#SBATCH --cpus-per-task=16
#SBATCH --time=5:00:00
#SBATCH --mem=10G
source /beegfs/home/tkastylevsky/.bashrc
PATH=/beegfs/home/tkastylevsky/.conda/envs/EDTA/bin:/beegfs/data/soft/anaconda3/bin:/beegfs/data/soft/REPET_linux-x64-3.0/bin:/beegfs/data/tkastylevsky/programs/:/beegfs/data/soft/singularity-3.1.1/bin:/beegfs/data/soft/bin:/beegfs/data/soft/mpiblast/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/beegfs/data/tkastylevsky/programs/EDTA
conda activate EDTA
cd /beegfs/data/tkastylevsky/genomes/EDTA/gallus_gallus/chr1/
EDTA_raw.pl --genome galgal6_chr1.fa --type tir --threads 16
```

Timothee

**Comment by Tkastylevsky** [comment] 2020-02-14 08:56
Yep, turned out alright ! Thanks a lot for the help and the great tool !

**Comment by oushujun** [comment] 2020-02-14 17:33
Thanks for your report. I think there is something wrong with the step-by-step method. I will check later. For the conda quick version, you can install the dependency in this way, then `git clone` the latest EDTA and use it instead of using the `ENV` version.

**Comment by stefaniehoho** [comment] 2020-02-16 19:51
Hi Shujun,

I came across a similar issue when I used conda install step by step method. The error messages included "from numpy.testing.nosetester import import_nose
ModuleNotFoundError: No module named 'numpy.testing.nosetester'" as well. I found this might be due to conda installed the latest version of numpy 1.18 which has already removed some functions that required by EDTA pipeline. I downgraded numpy to 1.16.4 and got a test run of EDTA_raw for TIR and Helitron to work without error. Hope my experience could help to solve this bug.

Best,
Yixuan

**Comment by oushujun** [comment] 2020-02-18 23:06
I experimented the step-by-step installation a little bit, the error was caused by incompatible python packages. By specifying the working version it should be good:

`conda install -n EDTA -y cd-hit repeatmodeler muscle mdust blast openjdk perl perl-text-soundex multiprocess regex tensorflow=1.14.0 keras=2.2.4 scikit-learn=0.19.0 biopython pandas glob2 python=3.6 tesorter genericrepeatfinder genometools-genometools ltr_retriever ltr_finder numpy=1.16.4`

I am closing this thread for now as the problem seems to be solved. Please reopen it if it persists.

Shujun

**Closed by oushujun** 2020-02-18 23:06 UTC
Labels: bug
