### ISSUE TITLE
Debug lines found in EDTA.pl

### ISSUE THREAD

**Issue by hsiaopei** [oushujun/EDTA#2] opened 2019-06-04 14:07 UTC
We tried to run the pipeline using our genome assembly fasta file, xxx.fa.  Unfortunately,
the error message showed up "xxx.fa.masked does not contain any sequences!" 
What's going on? 
Apparently, at line 48 of the code of EDTA.pl , "if (0){", should be changed to "if (1){".

**Comment by oushujun** [comment] 2019-06-04 15:15
Hi @hsiaopei ,

Thanks for testing `EDTA`! Currently we encounter some issues with [TIR-Learner](https://github.com/weijiaweijia/TIR-Learner-Rice), so the first module `EDTA_raw.pl`, as well as the `EDTA.pl`, are under a test mode. I am working with @weijiaweijia, the author of `TIR-Learner` and co-author of the EDTA manuscript, to resolve this issue. It should be fixed within this week. Sorry for the inconvenience.

Best,
Shujun

**Comment by oushujun** [comment] 2019-06-17 06:30
Dear @hsiaopei, @gabyrech, and @philippbayer,

Thank you for using EDTA. I just finished a major upgrade for the program including fixing the `TIR-Learner` issue. Please reinstall the EDTA package and help to test with your genomes. Please ignore the FASTA-Reader error (e.g. `FASTA-Reader: Ignoring invalid residues at position(s): On line 252: 520-746`) and `cp` `rm` errors for now. They are harmless to the result.

Please kindly let me know if you encounter any other errors. Thank you!

Best,
Shujun

**Comment by philippbayer** [comment] 2019-06-18 15:12
Thanks for the heads-up Shujun - I just pulled it and turned it on, it's currently running and will probably run for a few days (plant genome) :)

**Comment by philippbayer** [comment] 2019-06-20 06:52
I've now have had it running for about 24 hours:

    perl EDTA/EDTA.pl -genome ragoo.fasta -threads 15

currently it's hanging at this step: 

    perl <snip>/EDTA/bin/LTR_retriever/bin/LTR.identifier.pl ragoo.fasta -list ragoo.fasta.retriever.scn -seq ragoo.fasta.retriever.scn.extend.fa -anno ragoo.fasta.retriever.scn.extend.fa.aa.anno -flanksim 60 -flankmiss 25 -flankaln 0.6 -minlen 100 -u 1.3e-8 -threads 15 -blastplus /ws/00089503/anaconda/envs/EDTA/bin/ -motif TCCA TGCT TACA TACT TGGA TATA TGTA TGCA > ragoo.fasta.defalse

and is not consuming memory or CPU, and it hasn't written output in about 12 hours. The last file written was `ragoo.fasta.defalse` (my input is `ragoo.fasta`). Have you observed this before?

Last output in ragoo.fasta.defalse:

<pre>
Chr0_RaGOO:14387060..14401218   false   motif:TGAA      TSD:TCAG        14387056..14387059      14401219..14401222      IN:14387558..14400719   0.9779  ?       unknown NA      862315
        Adjust: NO      lLTR: 498       rLTR: 499
        Alignment regions: 1, 498, 13661, 14158
        LTR coordinates: 14387060, 14387557, 14400720, 14401218
        TSD-LTR overlap: 0
        Boundary missing: 0
</pre>

**Comment by oushujun** [comment] 2019-06-20 13:57
Hi Philipp,

This sounds not right for me. If the defalse step was finished, you should
be seeing a pass.list file, otherwise the LTR_retriever program is stuck in
the defalse step. This could happen when the specified cpus are not made
exclusive to the job (other jobs taking a lot of cpu resources), such that
the multithreading module couldn't allocate new threads to tasks. If this
is the case, the only way is to restart LTR_retriever or EDTA.

Best,
Shujun

**Comment by oushujun** [comment] 2019-08-01 21:38
Dear All,

Sorry for the delay of response. I just push a bulk update to EDTA and have tested it in different servers - it seems to work now. But I have not tested it in macOS, so some tiny differences could cause problems.

For testing purposes, please use a small file, ie. 20 Mb, for faster turn around. Please let me know if there are any issues. 

Best,
Shujun

**Comment by oushujun** [comment] 2019-08-16 20:54
I consider this issue is fixed. Please reopen it if the problem is persistent, or open new issues if you found new problems.

Best,
Shujun

**Closed by oushujun** 2019-08-16 20:54 UTC
Labels: bug, duplicate
