### ISSUE TITLE
hmmscan in TEsorter need hmmpress first

### ISSUE THREAD

**Issue by baozg** [oushujun/EDTA#121] opened 2020-10-10 08:27 UTC
Hi, @oushujun 

When using cds to clean up the TElib.fa, the TEsorter may throw the following error (have seen similiar error in other issues #105 )

```bash
b'\nError: Failed to open binary auxfiles for /data/software/conda_envs/EDTA/bin/python3.6/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm: use hmmpress first\n\n'
```

It need the first run the `hmmpress` for the hmm you use, run the following command:

```bash
# your conda envs
cd /data/software/conda_envs/EDTA/lib/python3.6/site-packages/TEsorter/database
for i in `ls *hmm | sed 's/.hmm//g'`; do hmmpress ${i}.hmm > ../${i}.hmm;done
```

**Comment by oushujun** [comment] 2020-10-12 04:04
@Juke34 @zhangrengang Is it possible to have this step done automatically during installation or the first-time use?

**Comment by Juke34** [comment] 2020-10-12 06:24
Yes it can be done in the conda recipe

**Comment by Juke34** [comment] 2020-10-30 09:02
It sounds @zhangrengang added this step in newer version of TEsorter.
See log when installing v1.3
```
SERR 2020-10-29 22:26:30,093 -INFO- check database rexdb
22:26:30 BIOCONDA INFO (ERR) [Oct 29 22:26:30] SERR 2020-10-29 22:26:30,094 -INFO- db path: /usr/local/lib/python3.9/site-packages/TEsorter/database
22:26:30 BIOCONDA INFO (ERR) [Oct 29 22:26:30] SERR 2020-10-29 22:26:30,094 -INFO- db file: REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm
22:26:30 BIOCONDA INFO (ERR) [Oct 29 22:26:30] SERR 2020-10-29 22:26:30,094 -INFO- db REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm not yet ready, building db!
22:26:30 BIOCONDA INFO (ERR) [Oct 29 22:26:30] SERR 2020-10-29 22:26:30,571 -INFO- Working...    done.
22:26:30 BIOCONDA INFO (ERR) [Oct 29 22:26:30] SERR Pressed and indexed 233 HMMs (233 names).
22:26:30 BIOCONDA INFO (ERR) [Oct 29 22:26:30] SERR Models pressed into binary file:   /usr/local/lib/python3.9/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm.h3m
22:26:30 BIOCONDA INFO (ERR) [Oct 29 22:26:30] SERR SSI index for binary model file:   /usr/local/lib/python3.9/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm.h3i
22:26:30 BIOCONDA INFO (ERR) [Oct 29 22:26:30] SERR Profiles (MSV part) pressed into:  /usr/local/lib/python3.9/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm.h3f
22:26:30 BIOCONDA INFO (ERR) [Oct 29 22:26:30] SERR Profiles (remainder) pressed into: /usr/local/lib/python3.9/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm.h3p
22:26:30 BIOCONDA INFO (ERR) [Oct 29 22:26:30] SERR
```

**Comment by Juke34** [comment] 2020-10-30 09:22
Apparently it was also present in previous version.
@baozg How did you install EDTA?
What are the commands to end up in this state? (i.e. what do you mean by `using cds to clean up the TElib.fa`).

**Comment by zhangrengang** [comment] 2020-10-30 09:49
Hi @Juke34. Can `hmmpress` or `build_database.sh` be run when installing but not when running at the first time? There is an issue  that non-root users have no permission to  build the database when running TEsorter (throwing `Error: failed to open SSI index *.hmm.h3i` when `hmmpress` and `Error: Failed to open binary auxfiles for *.hmm: use hmmpress first` when `hmmscan`) if it was installed by root. 
In this way, the issue #121 (maybe also caused by permission) should be also solved as all database have been present.

**Comment by Juke34** [comment] 2020-10-30 09:51
Ok I understand now why it is important to do so at the installation. Ok I will try to add it.

**Comment by oushujun** [comment] 2020-12-01 09:44
@Juke34 Any luck with adding `hmmpress` to the conda recipe?

**Comment by Juke34** [comment] 2020-12-01 20:19
Yes I did it last month, see above `Tesorter bioconda/bioconda-recipes#25148.  Merged`

**Comment by oushujun** [comment] 2020-12-03 02:42
I see. The Biocontainer's docker version of EDTA mentioned in #122 still has the `hmmpress` issue. I just check the `TEsorter` version in this docker image, it's `1.2.5.2`. Could it be that this image was created before TEsorter got updated and even I freshly pull it from the hub it is still using the old version of TEsorter?

**Comment by Juke34** [comment] 2020-12-03 09:20
Sure, the container has to be build after the modification. And as the EDTA container is made only when you release a new version of EDTA, if you did not release any new EDTA version since the hmmpress modification the EDTA container cannot embed the last version of the hmmpress dependency.

**Closed** 2020-12-06 04:12 UTC
Labels: enhancement
